package com.yyw.abc.ganhuo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yyw.abc.ganhuo.Gank;
import com.yyw.abc.ganhuo.Type;

import com.yyw.abc.ganhuo.GankDao;
import com.yyw.abc.ganhuo.TypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankDaoConfig;
    private final DaoConfig typeDaoConfig;

    private final GankDao gankDao;
    private final TypeDao typeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankDaoConfig = daoConfigMap.get(GankDao.class).clone();
        gankDaoConfig.initIdentityScope(type);

        typeDaoConfig = daoConfigMap.get(TypeDao.class).clone();
        typeDaoConfig.initIdentityScope(type);

        gankDao = new GankDao(gankDaoConfig, this);
        typeDao = new TypeDao(typeDaoConfig, this);

        registerDao(Gank.class, gankDao);
        registerDao(Type.class, typeDao);
    }
    
    public void clear() {
        gankDaoConfig.getIdentityScope().clear();
        typeDaoConfig.getIdentityScope().clear();
    }

    public GankDao getGankDao() {
        return gankDao;
    }

    public TypeDao getTypeDao() {
        return typeDao;
    }

}
