package com.yyw.abc.ganhuo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yyw.abc.ganhuo.Gank;

import com.yyw.abc.ganhuo.GankDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankDaoConfig;

    private final GankDao gankDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankDaoConfig = daoConfigMap.get(GankDao.class).clone();
        gankDaoConfig.initIdentityScope(type);

        gankDao = new GankDao(gankDaoConfig, this);

        registerDao(Gank.class, gankDao);
    }
    
    public void clear() {
        gankDaoConfig.getIdentityScope().clear();
    }

    public GankDao getGankDao() {
        return gankDao;
    }

}
