package com.yyw.abc.ganhuo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GANK".
 */
public class Gank {

    private Long id;
    /** Not-null value. */
    private String sid;
    private String url;
    private String who;
    private String type;
    private String publishedAt;
    private String desc;

    public Gank() {
    }

    public Gank(Long id) {
        this.id = id;
    }

    public Gank(Long id, String sid, String url, String who, String type, String publishedAt, String desc) {
        this.id = id;
        this.sid = sid;
        this.url = url;
        this.who = who;
        this.type = type;
        this.publishedAt = publishedAt;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSid() {
        return sid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getWho() {
        return who;
    }

    public void setWho(String who) {
        this.who = who;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
