package com.yyw.abc.ganhuo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TYPE".
 */
public class Type {

    private Long id;
    private int sid;
    /** Not-null value. */
    private String type;
    private boolean isChecked;

    public Type() {
    }

    public Type(Long id) {
        this.id = id;
    }

    public Type(Long id, int sid, String type, boolean isChecked) {
        this.id = id;
        this.sid = sid;
        this.type = type;
        this.isChecked = isChecked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSid() {
        return sid;
    }

    public void setSid(int sid) {
        this.sid = sid;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public boolean getIsChecked() {
        return isChecked;
    }

    public void setIsChecked(boolean isChecked) {
        this.isChecked = isChecked;
    }

}
